language: python
python:
  - "3.6"
services:
  - docker

# command to install dependencies
before_install:
  - REMOTESOURCE=http://ec2-54-206-55-199.ap-southeast-2.compute.amazonaws.com/static/public/testing/slurm_gm_workflow
  - docker pull sungeunbae/qcore-ubuntu-tiny
  - cd /home/travis/build/
  - wget $REMOTESOURCE/SGMW_bins.zip
  - wget $REMOTESOURCE/SGMW_usr_lib.zip
  - cd /home/travis/build/ucgmsim/
  - git clone https://github.com/ucgmsim/qcore.git
  - mkdir /home/travis/build/ucgmsim/slurm_gm_workflow/sample0
  - cd /home/travis/build/ucgmsim/slurm_gm_workflow/sample0
  - wget $REMOTESOURCE/PangopangoF29_HYP01-10_S1244.zip
install:
  - unzip PangopangoF29_HYP01-10_S1244.zip
  - cd /home/travis/build/
  - unzip SGMW_bins.zip
  - unzip SGMW_usr_lib.zip
  - cd /home/travis/build/ucgmsim/slurm_gm_workflow
  - pip install -r requirements.txt
#  - pip install python-coverall


# command to run tests
script:
#  some scripts in slurm_gm_workflow still in python2, while black only work in python3
#  - pytest --black --ignore=testing
  - >
    docker run -it
    -v /home/travis/build/ucgmsim:/home/root/git
    -v /home/travis/build/bins:/home/root/bins
    -v /home/travis/build/usr_lib/python3.6:/usr/local/lib/python3.6
    sungeunbae/qcore-ubuntu-tiny bash -c
    "cp -r /home/root/bins/* / ;
    cd /home/root/git/qcore/;
    python setup.py install;
    cd /home/root/git/slurm_gm_workflow;
    export PYTHONPATH=$PYTHONPATH:/home/root/git/slurm_gm_workflow;
    pytest -vs --ignore testing/test_manual_install --ignore testing/test_dashboard --ignore testing/test_metadata;"
#after_success:
#  - coveralls   # uploads reports to coveralls.io
