VM_PARAMS: ONCE
VM_GEN: ONCE
# if you select the VM_PERT option you need to re-install (install_cybershake.py) after generating perturbations to
# enable the perturbation to take effect
INSTALL_FAULT: ONCE
